name: GearedNomad
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36201146547682583
title: 'Geared Nomad | Where Digital Nomads, Photographers and Travelers share their passions'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffef'
    - '#17152c'
    - '#acd2c5'
    - '#395c7c'
    - '#69a8b1'
  brandStrength: 0.8763240261469036
  lightness: 0.9547805641777813
  saturation: 0.810439465334639
  rhythmicContrast: 0.15866246074438095
purpose: []
