name: GearedNomad
favicon: null
layout_spectrum: 0.48889
typography_spectrum: 0.5165
title: 'Geared Nomad | Where Digital Nomads, Photographers and Travelers share their passions'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#342b26'
    - '#564436'
    - '#786555'
    - '#887869'
    - '#998d81'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
